FROM docker.io/library/eclipse-temurin:25-jdk-alpine AS build
WORKDIR /workspace
COPY .mvn .mvn
COPY mvnw pom.xml ./
RUN chmod +x mvnw && ./mvnw -B -ntp dependency:go-offline
COPY src src
RUN ./mvnw -B -ntp clean package -DskipTests

FROM docker.io/library/eclipse-temurin:25-jre-alpine AS runtime
RUN addgroup -S crm && adduser -S -G crm -u 10001 crm
WORKDIR /app
COPY --from=build /workspace/target/crm-api-*.jar /app/crm-api.jar
USER 10001
EXPOSE 8081
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75.0", "-jar", "/app/crm-api.jar"]
